all: MediaPlayer MonPG1 MonPG2 MonPG3

MediaPlayer: MediaPlayer.c
	gcc -Wall -o ../MediaPlayer.exe MediaPlayer.c MediaPlayer.h

MonPG1: MonPG1.c
	gcc -Wall -o ../MonPG1 MonPG1.c

MonPG2: MonPG2.c
	gcc -Wall -o ../MonPG2 MonPG2.c

MonPG3: MonPG3.c
	gcc -Wall -o ../MonPG3 MonPG3.c
