all: MediaPlayer MonPG1 MonPG2

MediaPlayer: MediaPlayer.c
	gcc -o ../MediaPlayer MediaPlayer.c MediaPlayer.h

MonPG1: MonPG1.c
	gcc -o ../MonPG1 MonPG1.c

MonPG2: MonPG2.c
	gcc -o ../MonPG2 MonPG2.c
